[package]
name = "diagnostics"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base-db = { path = "../base-db" }
itertools = "0.10.5"
rowan = "0.15.11"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
url = "2.3.1"

[lib]
doctest = false
