[package]
name = "diagnostics"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base-db = { path = "../base-db" }
encoding_rs = "0.8.33"
encoding_rs_io = "0.1.7"
itertools = "0.12.0"
line-index = { path = "../line-index" }
log = "0.4.21"
multimap = "0.10.0"
once_cell = "1.19.0"
regex = "1.10.2"
rowan = "0.15.15"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
url = "2.5.0"

[dev-dependencies]
expect-test = "1.4.1"
test-utils = { path = "../test-utils" }

[lib]
doctest = false
