[package]
name = "texlab-protocol"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
dunce = "1.0"
futures = "0.3"
futures-boxed = { path = "../futures_boxed" }
jsonrpc = { path = "../jsonrpc" }
jsonrpc-derive = { path = "../jsonrpc_derive" }
log = "0.4.6"
lsp-types = { version = "0.73.0", features = ["proposed"] }
nom = "5.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
tokio = { version = "0.2", features = ["fs", "process", "time"] }
tokio-util = { version = "0.2", features = ["codec"] }
