[package]
name = "texlab-citeproc"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
html2md = "0.2.9"
lsp-types = { git = "https://github.com/latex-lsp/lsp-types", rev = "9fcc5d9b9d3013ce84e20ef566267754d594b268", features = ["proposed"] }
runtime = "0.3.0-alpha.4"
runtime-tokio = "0.3.0-alpha.4"
serde = { version = "1.0.97", features = ["derive", "rc"] }
tempfile = "3"
texlab-syntax = { path = "../texlab_syntax" }
tokio = "0.1"
tokio-process = "0.2.4"

