[package]
name = "texlab-syntax"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
itertools = "0.8.2"
once_cell = "1.2.0"
path-clean = "0.1.0"
serde = { version = "1.0.103", features = ["derive", "rc"] }
serde_json = "1.0.44"
texlab-distro = { path = "../texlab_distro" }
texlab-protocol = { path = "../texlab_protocol" }

[dev-dependencies]
indoc = "0.3.4"
