[package]
name = "parser"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
logos = "0.13.0"
once_cell = "1.18.0"
regex = "1.9.1"
rowan = "0.15.13"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
tempfile = "3.8.1"

[dev-dependencies]
expect-test = "1.4.1"

[lib]
doctest = false
