[package]
name = "parser"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
logos = "0.14.0"
once_cell = "1.19.0"
regex = "1.10.2"
rowan = "0.15.15"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
tempfile = "3.10.1"

[dev-dependencies]
expect-test = "1.4.1"

[lib]
doctest = false
