[package]
name = "parser"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
log = "0.4.22"
logos = "0.14.0"
once_cell = "1.19.0"
pathdiff = "0.2.1"
regex = "1.10.5"
rowan = "0.15.15"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
tempfile = "3.10.1"
versions = "6.3.0"

[dev-dependencies]
expect-test = "1.5.0"

[lib]
doctest = false
