[package]
name = "commands"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.71"
base-db = { path = "../base-db" }
bstr = "1.4.0"
crossbeam-channel = "0.5.8"
itertools = "0.10.5"
libc = "0.2.144"
log = "0.4.17"
rowan = "0.15.11"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
thiserror = "1.0.40"
url = "2.3.1"

[lib]
doctest = false
