[package]
name = "commands"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.86"
base-db = { path = "../base-db" }
bstr = "1.9.1"
crossbeam-channel = "0.5.12"
itertools = "0.12.1"
libc = "0.2.155"
log = "0.4.21"
rowan = "0.15.15"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
thiserror = "1.0.61"
url = "2.5.0"

[dev-dependencies]
distro = { path = "../distro" }
expect-test = "1.5.0"
test-utils = { path = "../test-utils" }

[lib]
doctest = false
