[package]
name = "texlab-test"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
copy_dir = "0.1.2"
futures = "0.3"
futures-boxed = { path = "../futures_boxed" }
jsonrpc = { path = "../jsonrpc" }
once_cell = "1.3.1"
serde = { version = "1.0.104", features = ["derive", "rc"] }
serde_json = "1.0.51"
tempfile = "3"
texlab = { path = "../.." }
texlab-distro = { path = "../texlab_distro" }
texlab-protocol = { path = "../texlab_protocol" }
tokio = { version = "0.2", features = ["fs", "process"] }
