[package]
name = "texlab-hover"
version = "0.1.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>",
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[dependencies]
base64 = "0.11.0"
futures = "0.3"
futures-boxed = { path = "../futures_boxed" }
image = "0.23.3"
log = "0.4.6"
tempfile = "3"
texlab-citeproc = { path = "../texlab_citeproc" }
texlab-distro = { path = "../texlab_distro" }
texlab-protocol = { path = "../texlab_protocol" }
texlab-syntax = { path = "../texlab_syntax" }
texlab-workspace = { path = "../texlab_workspace" }
tokio = { version = "0.2", features = ["fs", "process"] }
