[package]
name = "base-db"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
dirs = "5.0.1"
distro = { path = "../distro" }
itertools = "0.11.0"
log = "0.4.19"
notify = "6.0.1"
once_cell = "1.18.0"
parser = { path = "../parser" }
percent-encoding = "2.3.0"
regex = "1.9.1"
rowan = "0.15.11"
rustc-hash = "1.1.0"
syntax = { path = "../syntax" }
text-size = "1.1.1"
url = "=2.3.1"

[lib]
doctest = false
