[package]
name = "completion-data"
version = "0.0.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
flate2 = "1.0.28"
itertools = "0.11.0"
once_cell = "1.18.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.107"

[lib]
doctest = false
